In [1]:
import pandas as pd

In [2]:
zoom_csv = 'zoom-stock-prices-2019-04-01-2022-12-11.csv'
tweet_json = 'zm-6-2019-04-01-2022-12-11-all-zm-tweets.jsonl'

In [3]:
tweet_zm_df = pd.read_json(tweet_json, lines=True)

tweet_zm_df.head(10)

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,snscrape.modules.twitter.Tweet,https://twitter.com/nobbies_trading/status/160...,2022-12-10 23:34:47+00:00,$ROKU $ARKK $TWLO $AMZN $DIS $NVAX $NVDA $AMD ...,$ROKU $ARKK $TWLO $AMZN $DIS $NVAX $NVDA $AMD ...,1601722124674035716,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,1.601718e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...",None,None,None,None,"[ROKU, ARKK, TWLO, AMZN, DIS, NVAX, NVDA, AMD,..."
1,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601721...,2022-12-10 23:33:05+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601721696209489920,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
2,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601720...,2022-12-10 23:27:05+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601720184125157376,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
3,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601718...,2022-12-10 23:19:04+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601718168904699904,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
4,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601716...,2022-12-10 23:11:34+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601716279169417216,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
5,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601714...,2022-12-10 23:05:35+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601714774894866432,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
6,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601705...,2022-12-10 22:30:04+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601705837013397504,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
7,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601703...,2022-12-10 22:22:34+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601703949035540480,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
8,snscrape.modules.twitter.Tweet,https://twitter.com/beeken_tech/status/1601702...,2022-12-10 22:16:04+00:00,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,$ROKU $SQ $TSLA $ZM - 5 Investment Opportuniti...,1601702312216760320,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,0,...,None,NaN,None,NaN,None,None,None,None,None,"[ROKU, SQ, TSLA, ZM]"
9,snscrape.modules.twitter.Tweet,https://twitter.com/Trading_Sunset/status/1601...,2022-12-10 22:12:19+00:00,Zoom Video $ZM is currently -4.3% at $72.16.\n...,Zoom Video $ZM is currently -4.3% at $72.16.\n...,1601701371677671424,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,5,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,None,NaN,None,None,None,None,None,"[ZM, ARKK]"

In [4]:
# zoom_stock_prices_df = pd.read_csv(zoom_csv, on_bad_lines='skip') 
zoom_stock_prices_df = pd.read_csv(zoom_csv) 


zoom_stock_prices_df.shape

(920, 7)

# Exploring Tweets

In [6]:
tweet_zm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301098 entries, 0 to 301097
Data columns (total 28 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   _type             301098 non-null  object
 1   url               301098 non-null  object
 2   date              301098 non-null  datetime64[ns, UTC]
 3   content           301098 non-null  object
 4   renderedContent   301098 non-null  object
 5   id                301098 non-null  int64
 6   user              301098 non-null  object
 7   replyCount        301098 non-null  int64
 8   retweetCount      301098 non-null  int64
 9   likeCount         301098 non-null  int64
 10  quoteCount        301098 non-null  int64
 11  conversationId    301098 non-null  int64
 12  lang              301098 non-null  object
 13  source            301098 non-null  object
 14  sourceUrl         301098 non-null  object
 15  sourceLabel       301098 non-null  object
 16  outlinks          104914 non-null  object
 17  tcooutlinks       104914 non-null  object
 18  media             90458 non-null   object
 19  retweetedTweet    0 non-null       float64
 20  quotedTweet       22522 non-null   object
 21  inReplyToTweetId  48445 non-null   float64
 22  inReplyToUser     48445 non-null   object
 23  mentionedUsers    49517 non-null   object
 24  coordinates       2247 non-null    object
 25  place             2247 non-null    object
 26  hashtags          53340 non-null   object
 27  cashtags          300544 non-null  object
dtypes: datetime64[ns, UTC](1), float64(2), int64(6), object(19)
memory usage: 64.3+ MB

In [23]:
# tweet_zm_df[tweet_zm_df['date'].dt.year == 2020].shape

# getting tweets within 2020 and 2022
tweet_zm_2019_df = tweet_zm_df[tweet_zm_df['date'].dt.year == 2019]
tweet_zm_2020_df = tweet_zm_df[tweet_zm_df['date'].dt.year == 2020]
tweet_zm_2021_df = tweet_zm_df[tweet_zm_df['date'].dt.year == 2021]
tweet_zm_2022_df = tweet_zm_df[tweet_zm_df['date'].dt.year == 2022]



print('tweets 2019 - zm prices up due to covid')
print(tweet_zm_2019_df.shape)

print('tweets 2020 - zm prices up due to covid')
print(tweet_zm_2020_df.shape)

print('tweets 2021 - zm prices stable i think, but still high')
print(tweet_zm_2021_df.shape)

print('tweets 2022 - price goes down')
print(tweet_zm_2022_df.shape)

print ('notice the number of tweets per year is going down. But take note that \
     2022 is not full and 2019 is not full either as zm went public in april 2019')

print('next see each month tweets')

# once we get each month, test how many likes, retweets etc... and see if there a pattern.
# average price per month and how many tweets per that month.
# later we can check 1 week of sentiment to each 1 day of price.

tweets 2019 - zm prices up due to covid
(11063, 28)
tweets 2020 - zm prices up due to covid
(131544, 28)
tweets 2021 - zm prices stable i think, but still high
(104543, 28)
tweets 2022 - price goes down
(53948, 28)
notice the number of tweets per year is going down. But take note that      2022 is not full and 2019 is not full either as zm went public in april 2019 i think

In [28]:
# Trying Grouper

# group_by_month_tweet_df = tweet_zm_df.groupby(pd.Grouper(freq='M'))

# group_by_month_tweet_df.sum()


# simple method
group_by_month_tweet_df = tweet_zm_df.groupby([(tweet_zm_df.date.dt.year), (tweet_zm_df.date.dt.month)]).sum()


group_by_month_tweet_df

                     id  replyCount  retweetCount  likeCount  quoteCount  \
date date
2019 4     1.799247e+21       758.0         910.0     5256.0       215.0
     5     1.479797e+21       479.0         605.0     2983.0        92.0
     6     2.317482e+21       919.0        1607.0     6100.0       240.0
     7     1.700187e+21       555.0        1262.0     4665.0       139.0
     8     6.023162e+20       155.0         644.0     1699.0        72.0
     9     1.407688e+21       463.0         810.0     2936.0        74.0
     10    1.370108e+21       407.0         512.0     2965.0        83.0
     11    9.603706e+20       253.0         792.0     2367.0        88.0
     12    1.151575e+21       338.0         870.0     2694.0        89.0
2020 1     8.973002e+20       357.0         904.0     4365.0       101.0
     2     4.297945e+21      1688.0        3318.0    17065.0       646.0
     3     1.104679e+22      4484.0        5832.0    30734.0      1125.0
     4     1.708050e+22      7857.0        7506.0    40938.0      1607.0
     5     8.236272e+21      3323.0        4200.0    20755.0       805.0
     6     1.557517e+22      6932.0       21368.0    61896.0      7488.0
     7     9.239074e+21      3536.0        5382.0    30202.0       607.0
     8     1.377652e+22      6749.0        8449.0    56658.0      1594.0
     9     2.614281e+22     11290.0       13196.0    96351.0      2085.0
     10    2.249216e+22      8710.0        9900.0    84280.0      2017.0
     11    2.444110e+22     11790.0       10112.0   103919.0      3690.0
     12    1.692098e+22      8643.0        7675.0    77667.0      1879.0
2021 1     1.735802e+22      8925.0        9444.0    96336.0      1746.0
     2     1.236348e+22      6208.0        7253.0    66868.0      1365.0
     3     1.890478e+22      8156.0        9169.0    90982.0      2241.0
     4     8.398196e+21      3193.0        4435.0    38135.0       694.0
     5     8.286901e+21      3910.0        5214.0    42227.0      1005.0
     6     1.195230e+22      4453.0        5468.0    52777.0      1099.0
     7     1.108693e+22      4302.0        4661.0    48041.0       932.0
     8     1.607407e+22      6821.0        6914.0    72147.0      1446.0
     9     1.176194e+22      4510.0        3993.0    41029.0       918.0
     10    6.888223e+21      2848.0        2921.0    25828.0       446.0
     11    1.442057e+22      6425.0        6525.0    57046.0      1280.0
     12    9.393347e+21      3962.0        4079.0    32668.0       845.0
2022 1     5.930385e+21      2732.0        3649.0    24282.0       614.0
     2     5.713269e+21      3028.0        4152.0    31893.0       801.0
     3     5.974047e+21      2217.0        2154.0    17796.0       400.0
     4     3.095114e+21      1380.0        1463.0    12180.0       327.0
     5     9.726156e+21      4284.0        4246.0    33682.0       996.0
     6     5.938923e+21      1935.0        2670.0    17718.0       525.0
     7     4.901710e+21      1017.0        1582.0     9301.0       233.0
     8     1.167928e+22      3046.0        5135.0    25229.0       704.0
     9     7.345933e+21      1677.0        3533.0    17853.0       593.0
     10    7.542074e+21      1129.0         778.0     5600.0       115.0
     11    1.251344e+22      2553.0        3720.0    24031.0       730.0
     12    3.087934e+21       189.0         179.0     1288.0        19.0

           conversationId  retweetedTweet  inReplyToTweetId
date date
2019 4       1.798555e+21             0.0      2.348875e+20
     5       1.479730e+21             0.0      1.896542e+20
     6       2.317273e+21             0.0      3.236459e+20
     7       1.699558e+21             0.0      2.323967e+20
     8       6.021121e+20             0.0      8.371821e+19
     9       1.407478e+21             0.0      1.512314e+20
     10      1.369371e+21             0.0      2.025634e+20
     11      9.602195e+20             0.0      1.099844e+20
     12      1.151392e+21             0.0      1.096190e+20
2020 1       8.972800e+20             0.0      1.265880e+20
     2       4.297499e+21             0.0      8.180693e+20
     3       1.104590e+22             0.0      2.067301e+21
     4       1.707880e+22             0.0      3.120850e+21
     5       8.232611e+21             0.0      1.444769e+21
     6       1.557285e+22             0.0      2.458938e+21
     7       9.236941e+21             0.0      1.485768e+21
     8       1.377370e+22             0.0      2.330068e+21
     9       2.613970e+22             0.0      4.505496e+21
     10      2.248833e+22             0.0      3.730102e+21
     11      2.443649e+22             0.0      4.535874e+21
     12      1.691860e+22             0.0      3.560961e+21
2021 1       1.735502e+22             0.0      3.678131e+21
     2       1.236011e+22             0.0      2.606041e+21
     3       1.890147e+22             0.0      3.417965e+21
     4       8.396102e+21             0.0      1.367037e+21
     5       8.284556e+21             0.0      1.554141e+21
     6       1.194838e+22             0.0      1.770572e+21
     7       1.108489e+22             0.0      1.704250e+21
     8       1.607125e+22             0.0      2.447386e+21
     9       1.175881e+22             0.0      1.846159e+21
     10      6.886904e+21             0.0      1.068402e+21
     11      1.441832e+22             0.0      2.333615e+21
     12      9.391838e+21             0.0      1.612620e+21
2022 1       5.929093e+21             0.0      1.258227e+21
     2       5.712900e+21             0.0      8.428558e+20
     3       5.972915e+21             0.0      8.001364e+20
     4       3.094670e+21             0.0      5.014335e+20
     5       9.722416e+21             0.0      1.383058e+21
     6       5.937958e+21             0.0      6.541845e+20
     7       4.900933e+21             0.0      4.422073e+20
     8       1.167852e+22             0.0      9.832942e+20
     9       7.345481e+21             0.0      4.410881e+20
     10      7.541779e+21             0.0      3.840732e+20
     11      1.251305e+22             0.0      7.087122e+20
     12      3.087777e+21             0.0      9.905855e+19